// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';

const EvolinciteTaskStates = {
  "PENDING": "PENDING",
  "IN_PROGRESS": "IN_PROGRESS",
  "REVIEW": "REVIEW",
  "COMPLETE": "COMPLETE"
};

const EvolinciteActivityTypes = {
  "TASK": "TASK",
  "MEETING": "MEETING"
};

const EvolinciteTypeBankAccounts = {
  "AHORRO": "AHORRO",
  "CORRIENTE": "CORRIENTE"
};

const EvolinciteTicketState = {
  "OPEN": "OPEN",
  "SOLVING": "SOLVING",
  "CLOSED": "CLOSED"
};

const EvolinciteFunctionalities = {
  "WALLET_CORE_ROUTE": "WALLET_CORE_ROUTE",
  "WALLET_PAYMENT_ROUTE": "WALLET_PAYMENT_ROUTE",
  "WALLET_PAYMENT_LOAD_ALL": "WALLET_PAYMENT_LOAD_ALL",
  "WALLET_PAYMENT_CREATE": "WALLET_PAYMENT_CREATE",
  "WALLET_PAYMENT_EDIT": "WALLET_PAYMENT_EDIT",
  "WALLET_PAYMENT_DELETE": "WALLET_PAYMENT_DELETE",
  "WALLET_PAYMENT_PROCESS": "WALLET_PAYMENT_PROCESS",
  "WALLET_PAYMENT_REVERT": "WALLET_PAYMENT_REVERT",
  "WALLET_PAYMENT_UPLOAD_FILES": "WALLET_PAYMENT_UPLOAD_FILES",
  "WALLET_PAYMENT_EXPORT_FILES": "WALLET_PAYMENT_EXPORT_FILES",
  "WALLET_PAYMENT_LOAD_PERSONAL": "WALLET_PAYMENT_LOAD_PERSONAL",
  "WALLET_EXPENSE_ROUTE": "WALLET_EXPENSE_ROUTE",
  "WALLET_EXPENSE_LOAD_ALL": "WALLET_EXPENSE_LOAD_ALL",
  "WALLET_EXPENSE_CREATE": "WALLET_EXPENSE_CREATE",
  "WALLET_EXPENSE_EDIT": "WALLET_EXPENSE_EDIT",
  "WALLET_EXPENSE_DELETE": "WALLET_EXPENSE_DELETE",
  "WALLET_EXPENSE_PROCESS": "WALLET_EXPENSE_PROCESS",
  "WALLET_EXPENSE_TYPE_ROUTE": "WALLET_EXPENSE_TYPE_ROUTE",
  "WALLET_EXPENSE_TYPE_CREATE": "WALLET_EXPENSE_TYPE_CREATE",
  "WALLET_EXPENSE_TYPE_EDIT": "WALLET_EXPENSE_TYPE_EDIT",
  "WALLET_EXPENSE_TYPE_DELETE": "WALLET_EXPENSE_TYPE_DELETE",
  "WALLET_EXPENSE_REVERT": "WALLET_EXPENSE_REVERT",
  "WALLET_EXPENSE_LOAD_PERSONAL": "WALLET_EXPENSE_LOAD_PERSONAL",
  "WALLET_SALARY_ROUTE": "WALLET_SALARY_ROUTE",
  "WALLET_SALARY_PROCESS": "WALLET_SALARY_PROCESS",
  "WALLET_REPORTS_PAYMENTS_ACCESS": "WALLET_REPORTS_PAYMENTS_ACCESS",
  "WALLET_REPORTS_EXPENSES_ACCESS": "WALLET_REPORTS_EXPENSES_ACCESS",
  "WALLET_REPORTS_NEGOTIATIONS_ACCESS": "WALLET_REPORTS_NEGOTIATIONS_ACCESS",
  "WALLET_NEGOTIATIONS_DUPLICATED": "WALLET_NEGOTIATIONS_DUPLICATED",
  "WALLET_NEGOTIATIONS_EXPENSE": "WALLET_NEGOTIATIONS_EXPENSE",
  "CRM_CORE_ROUTE": "CRM_CORE_ROUTE",
  "CRM_PROCESS_ROUTE": "CRM_PROCESS_ROUTE",
  "CRM_STATE_CREATE": "CRM_STATE_CREATE",
  "CRM_STATE_EDIT": "CRM_STATE_EDIT",
  "CRM_STATE_DELETE": "CRM_STATE_DELETE",
  "CRM_PIPELINE_CREATE": "CRM_PIPELINE_CREATE",
  "CRM_PIPELINE_EDIT": "CRM_PIPELINE_EDIT",
  "CRM_PIPELINE_DELETE": "CRM_PIPELINE_DELETE",
  "CRM_COMMENTARY_CREATE": "CRM_COMMENTARY_CREATE",
  "CRM_COMMENTARY_SELECT_FILE": "CRM_COMMENTARY_SELECT_FILE",
  "CRM_COMMENTARY_SELECT_EMOJI": "CRM_COMMENTARY_SELECT_EMOJI",
  "CRM_COMMENTARY_DELETE_ALL": "CRM_COMMENTARY_DELETE_ALL",
  "CRM_COPY_NEGOTIATION": "CRM_COPY_NEGOTIATION",
  "CRM_MOVE_NEGOTIATION": "CRM_MOVE_NEGOTIATION",
  "CRM_COPY_NEGOTIATION_MASSIVE": "CRM_COPY_NEGOTIATION_MASSIVE",
  "CRM_MOVE_NEGOTIATION_MASSIVE": "CRM_MOVE_NEGOTIATION_MASSIVE",
  "CRM_FROZEN_NEGOTIATION": "CRM_FROZEN_NEGOTIATION",
  "CRM_FIELD_MANAGER_CORE_ROUTE": "CRM_FIELD_MANAGER_CORE_ROUTE",
  "CRM_FIELD_MANAGER_SECTION_CREATE": "CRM_FIELD_MANAGER_SECTION_CREATE",
  "CRM_FIELD_MANAGER_FIELD_CREATE": "CRM_FIELD_MANAGER_FIELD_CREATE",
  "CRM_FIELD_MANAGER_FIELD_AND_SECTION_EDIT": "CRM_FIELD_MANAGER_FIELD_AND_SECTION_EDIT",
  "CRM_FIELD_MANAGER_FIELD_AND_SECTION_DELETE": "CRM_FIELD_MANAGER_FIELD_AND_SECTION_DELETE",
  "CRM_AUTOMATION_CORE_ROUTE": "CRM_AUTOMATION_CORE_ROUTE",
  "CRM_AUTOMATION_CREATE": "CRM_AUTOMATION_CREATE",
  "CRM_AUTOMATION_EDIT": "CRM_AUTOMATION_EDIT",
  "CRM_AUTOMATION_DELETE": "CRM_AUTOMATION_DELETE",
  "CRM_CONFIGURATIONS_ACCESS_PERMITS_CRM": "CRM_CONFIGURATIONS_ACCESS_PERMITS_CRM",
  "CRM_PROCESS_TYPE_CORE_ROUTE": "CRM_PROCESS_TYPE_CORE_ROUTE",
  "CRM_PROCESS_TYPE_CREATE": "CRM_PROCESS_TYPE_CREATE",
  "CRM_PROCESS_TYPE_EDIT": "CRM_PROCESS_TYPE_EDIT",
  "CRM_PROCESS_TYPE_DELETE": "CRM_PROCESS_TYPE_DELETE",
  "CRM_NEGOTIATION_CREATE": "CRM_NEGOTIATION_CREATE",
  "CRM_NEGOTIATION_EDIT": "CRM_NEGOTIATION_EDIT",
  "CRM_NEGOTIATION_DELETE": "CRM_NEGOTIATION_DELETE",
  "CRM_NEGOTIATION_PARENT_ACCESS": "CRM_NEGOTIATION_PARENT_ACCESS",
  "CRM_NEGOTIATION_PARENT_CHANGE": "CRM_NEGOTIATION_PARENT_CHANGE",
  "CRM_NEGOTIATION_PARENT_UNLINK": "CRM_NEGOTIATION_PARENT_UNLINK",
  "CRM_NEGOTIATION_EDIT_AMOUNTS": "CRM_NEGOTIATION_EDIT_AMOUNTS",
  "CRM_NEGOTIATION_GOAL_CREATE": "CRM_NEGOTIATION_GOAL_CREATE",
  "CRM_NEGOTIATION_GOAL_EDIT": "CRM_NEGOTIATION_GOAL_EDIT",
  "CRM_NEGOTIATION_GOAL_DELETE": "CRM_NEGOTIATION_GOAL_DELETE",
  "CRM_NEGOTIATION_GOAL_ADD": "CRM_NEGOTIATION_GOAL_ADD",
  "CRM_NEGOTIATION_GOAL_CHANGE": "CRM_NEGOTIATION_GOAL_CHANGE",
  "CRM_NEGOTIATION_VIEW_GENERAL_INFORMATION": "CRM_NEGOTIATION_VIEW_GENERAL_INFORMATION",
  "CRM_CUSTOMER_CREATE": "CRM_CUSTOMER_CREATE",
  "CRM_CUSTOMER_EDIT": "CRM_CUSTOMER_EDIT",
  "CRM_CUSTOMER_DELETE": "CRM_CUSTOMER_DELETE",
  "CALENDAR_CORE_ROUTE": "CALENDAR_CORE_ROUTE",
  "CALENDAR_ACTIVITY_CREATE": "CALENDAR_ACTIVITY_CREATE",
  "CALENDAR_ACTIVITY_EDIT": "CALENDAR_ACTIVITY_EDIT",
  "CALENDAR_ACTIVITY_DELETE": "CALENDAR_ACTIVITY_DELETE",
  "CALENDAR_VIEW_OTHER_USER": "CALENDAR_VIEW_OTHER_USER",
  "TASK_CORE_ROUTE": "TASK_CORE_ROUTE",
  "TASK_CHANGE_STATE": "TASK_CHANGE_STATE",
  "TASK_KANBAN_CORE_ROUTE": "TASK_KANBAN_CORE_ROUTE",
  "TASK_LIST_VIEW_CORE_ROUTE": "TASK_LIST_VIEW_CORE_ROUTE",
  "TASK_KANBAN_VIEW_CORE_ROUTE": "TASK_KANBAN_VIEW_CORE_ROUTE",
  "COMPANY_CORE_ROUTE": "COMPANY_CORE_ROUTE",
  "COMPANY_ORGANIZATION_ROUTE": "COMPANY_ORGANIZATION_ROUTE",
  "COMPANY_DEPARTMENT_CREATE": "COMPANY_DEPARTMENT_CREATE",
  "COMPANY_DEPARTMENT_EDIT": "COMPANY_DEPARTMENT_EDIT",
  "COMPANY_DEPARTMENT_DELETE": "COMPANY_DEPARTMENT_DELETE",
  "COMPANY_EMPLOYEES_ROUTE": "COMPANY_EMPLOYEES_ROUTE",
  "COMPANY_EMPLOYEE_CREATE": "COMPANY_EMPLOYEE_CREATE",
  "COMPANY_EMPLOYEE_EDIT": "COMPANY_EMPLOYEE_EDIT",
  "COMPANY_EMPLOYEE_DELETE": "COMPANY_EMPLOYEE_DELETE",
  "COMPANY_EMPLOYEE_INVITE_USER": "COMPANY_EMPLOYEE_INVITE_USER",
  "COMPANY_EMPLOYEE_JOB_CREATE": "COMPANY_EMPLOYEE_JOB_CREATE",
  "COMPANY_EMPLOYEE_JOB_EDIT": "COMPANY_EMPLOYEE_JOB_EDIT",
  "COMPANY_EMPLOYEE_JOB_DELETE": "COMPANY_EMPLOYEE_JOB_DELETE",
  "COMPANY_REASSIGN_DATA": "COMPANY_REASSIGN_DATA",
  "CHAT_CORE_ROUTE": "CHAT_CORE_ROUTE",
  "CHAT_SELECT_EMOJI": "CHAT_SELECT_EMOJI",
  "CHAT_SELECT_FILE": "CHAT_SELECT_FILE",
  "CHAT_SEND_MESSAGE": "CHAT_SEND_MESSAGE",
  "MAIL_CORE_ROUTE": "MAIL_CORE_ROUTE",
  "MAIL_INBOX_ROUTE": "MAIL_INBOX_ROUTE",
  "MAIL_COMPOSE_ROUTE": "MAIL_COMPOSE_ROUTE",
  "MAIL_DETAIL_ROUTE": "MAIL_DETAIL_ROUTE",
  "FILES_CORE_ROUTE": "FILES_CORE_ROUTE",
  "FILES_CREATE_FILE": "FILES_CREATE_FILE",
  "FILES_EDIT_FILE": "FILES_EDIT_FILE",
  "FILES_DELETE_FILE": "FILES_DELETE_FILE",
  "FILES_CREATE_FILE_ALL": "FILES_CREATE_FILE_ALL",
  "FILES_EDIT_FILE_ALL": "FILES_EDIT_FILE_ALL",
  "FILES_DELETE_FILE_ALL": "FILES_DELETE_FILE_ALL",
  "FILES_VIEW_FILE": "FILES_VIEW_FILE",
  "FILES_CREATE_FOLDER": "FILES_CREATE_FOLDER",
  "FILES_EDIT_FOLDER": "FILES_EDIT_FOLDER",
  "FILES_DELETE_FOLDER": "FILES_DELETE_FOLDER",
  "FILES_CREATE_FOLDER_ALL": "FILES_CREATE_FOLDER_ALL",
  "FILES_EDIT_FOLDER_ALL": "FILES_EDIT_FOLDER_ALL",
  "FILES_DELETE_FOLDER_ALL": "FILES_DELETE_FOLDER_ALL",
  "FILES_MOVE_FILE_AND_FOLDER": "FILES_MOVE_FILE_AND_FOLDER",
  "FILES_MOVE_FILE_AND_FOLDER_ALL": "FILES_MOVE_FILE_AND_FOLDER_ALL",
  "FORUM_CORE_ROUTE": "FORUM_CORE_ROUTE",
  "FORUM_CREATE_ARTICLE": "FORUM_CREATE_ARTICLE",
  "FORUM_EDIT_ARTICLE": "FORUM_EDIT_ARTICLE",
  "FORUM_DELETE_ARTICLE": "FORUM_DELETE_ARTICLE",
  "FORUM_EDIT_ARTICLE_ALL": "FORUM_EDIT_ARTICLE_ALL",
  "FORUM_DELETE_ARTICLE_ALL": "FORUM_DELETE_ARTICLE_ALL",
  "SURVEY_CORE_ROUTE": "SURVEY_CORE_ROUTE",
  "SURVEY_VIEW_FORM": "SURVEY_VIEW_FORM",
  "SURVEY_CREATE_FORM": "SURVEY_CREATE_FORM",
  "SURVEY_EDIT_FORM": "SURVEY_EDIT_FORM",
  "SURVEY_DELETE_FORM": "SURVEY_DELETE_FORM",
  "SURVEY_VIEW_ANSWERS": "SURVEY_VIEW_ANSWERS",
  "SURVEY_DELETE_ANSWER": "SURVEY_DELETE_ANSWER",
  "SURVEY_PROCESS_ANSWER": "SURVEY_PROCESS_ANSWER",
  "ACCESS_CORE_ROUTE": "ACCESS_CORE_ROUTE",
  "ACCESS_CREATE": "ACCESS_CREATE",
  "ACCESS_EDIT": "ACCESS_EDIT",
  "ACCESS_DELETE": "ACCESS_DELETE",
  "CONFIG_CORE_ROUTE": "CONFIG_CORE_ROUTE",
  "CONFIG_GENERAL": "CONFIG_GENERAL",
  "CONFIG_PROCESS_TYPE": "CONFIG_PROCESS_TYPE",
  "CONFIG_GOALS": "CONFIG_GOALS",
  "CONFIG_JOB_TITLE": "CONFIG_JOB_TITLE",
  "CONFIG_CUSTOMER": "CONFIG_CUSTOMER",
  "CONFIG_CUSTOMER_DELETE": "CONFIG_CUSTOMER_DELETE",
  "CONFIG_PAYMENT_AUTOMATION": "CONFIG_PAYMENT_AUTOMATION",
  "CONFIG_PAYMENT_AUTOMATION_CREATE": "CONFIG_PAYMENT_AUTOMATION_CREATE",
  "CONFIG_PAYMENT_AUTOMATION_EDIT": "CONFIG_PAYMENT_AUTOMATION_EDIT",
  "CONFIG_PAYMENT_AUTOMATION_DELETE": "CONFIG_PAYMENT_AUTOMATION_DELETE",
  "CONFIG_DEPARTMENTS": "CONFIG_DEPARTMENTS",
  "CONFIG_DEPARTMENT_CREATE": "CONFIG_DEPARTMENT_CREATE",
  "CONFIG_DEPARTMENT_EDIT": "CONFIG_DEPARTMENT_EDIT",
  "CONFIG_DEPARTMENT_DELETE": "CONFIG_DEPARTMENT_DELETE",
  "CONFIG_NEGOTIATIONS": "CONFIG_NEGOTIATIONS",
  "CONFIG_NEGOTIATION_CREATE": "CONFIG_NEGOTIATION_CREATE",
  "CONFIG_NEGOTIATION_EDIT": "CONFIG_NEGOTIATION_EDIT",
  "CONFIG_NEGOTIATION_DELETE": "CONFIG_NEGOTIATION_DELETE",
  "TICKETS_VIEW_ALL": "TICKETS_VIEW_ALL",
  "ACADEMY_CORE_ROUTE": "ACADEMY_CORE_ROUTE",
  "ACADEMY_COURSES_ROUTE": "ACADEMY_COURSES_ROUTE",
  "ACADEMY_WORKSHOPS_ROUTE": "ACADEMY_WORKSHOPS_ROUTE",
  "ACADEMY_ANSWERS_ROUTE": "ACADEMY_ANSWERS_ROUTE",
  "ACADEMY_ADMIN_ANSWERS_ROUTE": "ACADEMY_ADMIN_ANSWERS_ROUTE",
  "ACADEMY_ADMIN_ANSWERS_ALL_ROUTE": "ACADEMY_ADMIN_ANSWERS_ALL_ROUTE",
  "CORPORATE_MANAGEMENT_CORE": "CORPORATE_MANAGEMENT_CORE",
  "CORPORATE_MANAGEMENT_TIME": "CORPORATE_MANAGEMENT_TIME",
  "CORPORATE_MANAGEMENT_TIME_CREATE": "CORPORATE_MANAGEMENT_TIME_CREATE",
  "CORPORATE_MANAGEMENT_TIME_EDIT": "CORPORATE_MANAGEMENT_TIME_EDIT",
  "CORPORATE_MANAGEMENT_TIME_DELETE": "CORPORATE_MANAGEMENT_TIME_DELETE",
  "CORPORATE_MANAGEMENT_MILESTONE": "CORPORATE_MANAGEMENT_MILESTONE",
  "CORPORATE_MANAGEMENT_MILESTONE_CREATE": "CORPORATE_MANAGEMENT_MILESTONE_CREATE",
  "CORPORATE_MANAGEMENT_MILESTONE_EDIT": "CORPORATE_MANAGEMENT_MILESTONE_EDIT",
  "CORPORATE_MANAGEMENT_MILESTONE_DELETE": "CORPORATE_MANAGEMENT_MILESTONE_DELETE",
  "CORPORATE_MANAGEMENT_MILESTONE_VIEW_DETAILS": "CORPORATE_MANAGEMENT_MILESTONE_VIEW_DETAILS",
  "REQUEST_TEMPLATE_CORE_ROUTE": "REQUEST_TEMPLATE_CORE_ROUTE",
  "REQUEST_TEMPLATE_CREATE": "REQUEST_TEMPLATE_CREATE",
  "REQUEST_TEMPLATE_EDIT": "REQUEST_TEMPLATE_EDIT",
  "REQUEST_TEMPLATE_DELETE": "REQUEST_TEMPLATE_DELETE",
  "REQUEST_CORE_ROUTE": "REQUEST_CORE_ROUTE",
  "REQUEST_CREATE": "REQUEST_CREATE",
  "REQUEST_EDIT": "REQUEST_EDIT",
  "REQUEST_DELETE": "REQUEST_DELETE",
  "TAG_CORE_ROUTE": "TAG_CORE_ROUTE",
  "TAG_CREATE": "TAG_CREATE",
  "TAG_EDIT": "TAG_EDIT",
  "TAG_DELETE": "TAG_DELETE"
};

const EvolinciteTransactionType = {
  "CREDIT_CARD": "CREDIT_CARD",
  "WIRE_TRANSFER": "WIRE_TRANSFER",
  "CASH": "CASH",
  "WEB_PAY": "WEB_PAY",
  "BANK_DEPOSIT": "BANK_DEPOSIT",
  "CORRESPONDENT_DEPOSIT": "CORRESPONDENT_DEPOSIT"
};

const EvolinciteLogicOperator = {
  "EXIST": "EXIST",
  "NOT_EXIST": "NOT_EXIST",
  "EQUAL": "EQUAL",
  "NOT_EQUAL": "NOT_EQUAL",
  "GREATER_THAN": "GREATER_THAN",
  "SMALLER_THAN": "SMALLER_THAN"
};

const EvolinciteExpenseStates = {
  "PENDING": "PENDING",
  "PAID": "PAID",
  "VALIDATE": "VALIDATE"
};

const EvolinciteFieldCore = {
  "NAME": "NAME",
  "VALUE": "VALUE",
  "OWNER": "OWNER"
};

const EvolinciteMunicipality = {
  "CUCUTA": "CUCUTA",
  "BUCARAMANGA": "BUCARAMANGA",
  "LETICIA": "LETICIA",
  "MEDELLIN": "MEDELLIN",
  "ARAUCA": "ARAUCA",
  "BARRANQUILLA": "BARRANQUILLA",
  "BOGOTA": "BOGOTA",
  "CARTAGENA": "CARTAGENA",
  "TUNJA": "TUNJA",
  "MANIZALES": "MANIZALES",
  "FLORENCIA": "FLORENCIA",
  "YOPAL": "YOPAL",
  "POPAYAN": "POPAYAN",
  "VALLEDUPAR": "VALLEDUPAR",
  "QUIBDO": "QUIBDO",
  "MONTERIA": "MONTERIA",
  "INIRIDA": "INIRIDA",
  "SAN_JOSE_DEL_GUAVIARE": "SAN_JOSE_DEL_GUAVIARE",
  "NEIVA": "NEIVA",
  "RIOACHA": "RIOACHA",
  "SANTA_MARTA": "SANTA_MARTA",
  "VILLAVICENCIO": "VILLAVICENCIO",
  "PASTO": "PASTO",
  "MOCOA": "MOCOA",
  "ARMENIA": "ARMENIA",
  "PEREIRA": "PEREIRA",
  "SAN_ANDRES": "SAN_ANDRES",
  "SINCELEJO": "SINCELEJO",
  "IBAGUE": "IBAGUE",
  "CALI": "CALI",
  "MITU": "MITU",
  "PUERTO_CARRENO": "PUERTO_CARRENO"
};

const EvolinciteDocumentType = {
  "CC": "CC",
  "NIT": "NIT"
};

const EvolinciteWalletPaymentStatus = {
  "PAID": "PAID",
  "PENDING": "PENDING",
  "VALIDATE": "VALIDATE",
  "REVERTED": "REVERTED"
};

const EvolinciteField = {
  "STRING": "STRING",
  "NUMBER": "NUMBER",
  "SELECT_LIST": "SELECT_LIST",
  "DOCUMENT": "DOCUMENT",
  "DATE": "DATE"
};

const EvolinciteMessageType = {
  "TEXT": "TEXT",
  "IMG": "IMG",
  "FILE": "FILE",
  "VIDEO": "VIDEO"
};

const EvolinciteRule = {
  "MOVE": "MOVE",
  "COPY": "COPY",
  "CHANGE_ATTRIBUTE": "CHANGE_ATTRIBUTE",
  "CREATE_PAYMENT": "CREATE_PAYMENT",
  "CREATE_EXPENSE": "CREATE_EXPENSE",
  "VALIDATE_FIELD": "VALIDATE_FIELD",
  "FROZEN_NEGOTIATION": "FROZEN_NEGOTIATION",
  "ASSIGN_GOAL_INITIAL": "ASSIGN_GOAL_INITIAL",
  "ASSIGN_GOAL_FINAL": "ASSIGN_GOAL_FINAL",
  "CREATE_NEGOTIATION": "CREATE_NEGOTIATION",
  "VALIDATE_TOTAL_TASKS": "VALIDATE_TOTAL_TASKS",
  "VALIDATE_TASK_STATE": "VALIDATE_TASK_STATE",
  "VALIDATE_TASKS_SPECIFIC_STATE": "VALIDATE_TASKS_SPECIFIC_STATE",
  "SEND_PRE_MADE_EMAIL": "SEND_PRE_MADE_EMAIL",
  "SEND_CREATE_EMAIL": "SEND_CREATE_EMAIL",
  "GENERATE_DOCUMENT": "GENERATE_DOCUMENT",
  "CONTROL_CRM_STATES": "CONTROL_CRM_STATES"
};

const EvolinciteStates = {
  "INACTIVE": "INACTIVE",
  "ACTIVE": "ACTIVE"
};

const EvolinciteApplication = {
  "LEADS_UP": "LEADS_UP",
  "ACADEMY": "ACADEMY",
  "LANDING": "LANDING"
};

const EvolinciteArticleStates = {
  "INTERNAL": "INTERNAL",
  "EXTERNAL": "EXTERNAL"
};

const EvolinciteNotificationPriority = {
  "HIGH": "HIGH",
  "MEDIUM": "MEDIUM",
  "LOW": "LOW"
};

const EvolinciteMailStates = {
  "PENDING": "PENDING",
  "SENT": "SENT",
  "REJECTED": "REJECTED"
};

const EvolinciteSurveyAnswerState = {
  "PROCESS": "PROCESS",
  "NO_PROCESS": "NO_PROCESS",
  "NO_CRM": "NO_CRM"
};

const EvolunciteNotificationType = {
  "GENERAL": "GENERAL",
  "NEGOTIATION": "NEGOTIATION",
  "CHAT": "CHAT"
};

const EvolunciteMilestoneType = {
  "AMOUNT": "AMOUNT",
  "CLIENTS": "CLIENTS",
  "PROCESSES": "PROCESSES",
  "GOALS": "GOALS",
  "TASKS": "TASKS"
};

const EvolunciteRequestType = {
  "NEGOTIATION": "NEGOTIATION",
  "PAY": "PAY",
  "EXPENSE": "EXPENSE",
  "GENERAL": "GENERAL"
};

const EvolinciteRequestPriority = {
  "HIGH": "HIGH",
  "MEDIUM": "MEDIUM",
  "LOW": "LOW"
};

const EvolinciteRequestStatus = {
  "ACCEPTED": "ACCEPTED",
  "REJECTED": "REJECTED"
};

const { EvolinciteCompetence, EvolinciteCourse, EvolinciteSyllabus, EvolinciteUserAnswers, EvolinciteProcessType, EvolinciteExpenseType, EvolinciteExpense, EvolinciteUserEvolinciteJobTitle, EvolinciteJobTitle, EvolinciteWalletPayment, EvolinciteCrmNegotiationField, EvolinciteCrmNegotiationSection, EvolinciteCrmAutomation, EvolinciteComment, EvolinciteActivity, EvolincitePermissions, EvolinciteDepartment, EvolinciteSubscription, EvolinciteModule, EvolinciteFunctionality, EvolinciteRol, EvolinciteCustomer, EvolinciteUserSettings, EvolinciteCrmPipeline, EvolinciteCrmState, EvolinciteCrmNegotiationLog, EvolinciteCrmNegotiation, EvolinciteRoom, EvolinciteMessage, EvolinciteCrmNegotiationFieldValue, EvolinciteEmail, EvolinciteEmailTemplate, EvolinciteNotification, EvolinciteUserDepartment, EvolinciteUserEvolinciteCompany, EvolinciteUser, EvolinciteCompany, EvolinciteGoal, EvolinciteWalletPaymentLog, EvolinciteExpenseLog, EvolinciteTicket, EvolinciteTicketLog, EvolinciteFile, EvolinciteFolder, EvolinciteArticle, EvolinciteArticleComment, EvolinciteFormConfiguration, EvolinciteFormAnswer, EvolincitePaymentAutomation, EvolinciteMail, EvolinciteMailConfiguration, EvolinciteMailTemplate, EvolinciteMailTemplateLog, EvolincitePackage, EvolinciteCompanySubscription, EvolinciteEmployeeObservation, EvolinciteTag, EvolinciteMilestone, EvolinciteUserLog, EvolinciteUserTimeTracking, EvolinciteSchedule, EvolinciteTemplateRequest, EvolinciteRequest, EvolinciteActivityEvolinciteUser, EvolinciteUserEvolinciteCrmNegotiation, EvolinciteRoomEvolinciteUser } = initSchema(schema);

export {
  EvolinciteCompetence,
  EvolinciteCourse,
  EvolinciteSyllabus,
  EvolinciteUserAnswers,
  EvolinciteProcessType,
  EvolinciteExpenseType,
  EvolinciteExpense,
  EvolinciteUserEvolinciteJobTitle,
  EvolinciteJobTitle,
  EvolinciteWalletPayment,
  EvolinciteCrmNegotiationField,
  EvolinciteCrmNegotiationSection,
  EvolinciteCrmAutomation,
  EvolinciteComment,
  EvolinciteActivity,
  EvolincitePermissions,
  EvolinciteDepartment,
  EvolinciteSubscription,
  EvolinciteModule,
  EvolinciteFunctionality,
  EvolinciteRol,
  EvolinciteCustomer,
  EvolinciteUserSettings,
  EvolinciteCrmPipeline,
  EvolinciteCrmState,
  EvolinciteCrmNegotiationLog,
  EvolinciteCrmNegotiation,
  EvolinciteRoom,
  EvolinciteMessage,
  EvolinciteCrmNegotiationFieldValue,
  EvolinciteEmail,
  EvolinciteEmailTemplate,
  EvolinciteNotification,
  EvolinciteUserDepartment,
  EvolinciteUserEvolinciteCompany,
  EvolinciteUser,
  EvolinciteCompany,
  EvolinciteGoal,
  EvolinciteWalletPaymentLog,
  EvolinciteExpenseLog,
  EvolinciteTicket,
  EvolinciteTicketLog,
  EvolinciteFile,
  EvolinciteFolder,
  EvolinciteArticle,
  EvolinciteArticleComment,
  EvolinciteFormConfiguration,
  EvolinciteFormAnswer,
  EvolincitePaymentAutomation,
  EvolinciteMail,
  EvolinciteMailConfiguration,
  EvolinciteMailTemplate,
  EvolinciteMailTemplateLog,
  EvolincitePackage,
  EvolinciteCompanySubscription,
  EvolinciteEmployeeObservation,
  EvolinciteTag,
  EvolinciteMilestone,
  EvolinciteUserLog,
  EvolinciteUserTimeTracking,
  EvolinciteSchedule,
  EvolinciteTemplateRequest,
  EvolinciteRequest,
  EvolinciteActivityEvolinciteUser,
  EvolinciteUserEvolinciteCrmNegotiation,
  EvolinciteRoomEvolinciteUser,
  EvolinciteTaskStates,
  EvolinciteActivityTypes,
  EvolinciteTypeBankAccounts,
  EvolinciteTicketState,
  EvolinciteFunctionalities,
  EvolinciteTransactionType,
  EvolinciteLogicOperator,
  EvolinciteExpenseStates,
  EvolinciteFieldCore,
  EvolinciteMunicipality,
  EvolinciteDocumentType,
  EvolinciteWalletPaymentStatus,
  EvolinciteField,
  EvolinciteMessageType,
  EvolinciteRule,
  EvolinciteStates,
  EvolinciteApplication,
  EvolinciteArticleStates,
  EvolinciteNotificationPriority,
  EvolinciteMailStates,
  EvolinciteSurveyAnswerState,
  EvolunciteNotificationType,
  EvolunciteMilestoneType,
  EvolunciteRequestType,
  EvolinciteRequestPriority,
  EvolinciteRequestStatus
};